import { useState } from 'react';
import './features.css';

const REPO = 'https://github.com/fuckramochka/miogram';
const categories = [
  { id: 'all', label: 'Всё сразу', symbol: '✧' },
  { id: 'privacy', label: 'Приватность', symbol: '♡' },
  { id: 'style', label: 'Твой стиль', symbol: '✿' },
  { id: 'tools', label: 'Инструменты', symbol: '⌘' },
  { id: 'ai', label: 'Умные фичи', symbol: '✦' },
];
const items = [
  { id: 'vault', category: 'privacy', symbol: '▣', name: 'Двойное хранилище', tag: 'double bottom', text: 'Личное остаётся личным. Два пространства и отдельный PIN.', detail: 'Обычный PIN открывает основное пространство, а Duress PIN — нейтральный экран. Двойное хранилище помогает отделить настоящий рабочий контекст от резервного. Особенности защиты и требования к устройству смотри в документации.' },
  { id: 'plugins', category: 'tools', symbol: '⌘', name: 'MioHook + exteraGram', tag: 'plugin power', text: 'Поддержка плагинов систем MioHook и exteraGram. Расширяй свой клиент.', detail: 'Добавляй нужные возможности через плагины MioHook и exteraGram. Совместимость конкретного плагина зависит от его версии и сборки клиента. Устанавливай расширения из доверенных источников и проверяй запрашиваемые разрешения.' },
  { id: 'customization', category: 'style', symbol: '✿', name: 'Глубокая кастомизация', tag: 'make it yours', text: 'Темы, цвета и детали. Твой MioGram не обязан быть похож на чужой.', detail: 'Настраивай оформление под себя, а не себя под оформление. Пользовательские темы Telegram и настройки внешнего вида дополняют разные варианты интерфейса. Ниже на сайте можно попробовать три цветовые палитры в демо.' },
  { id: 'music', category: 'tools', symbol: '♫', name: 'Свой музыкальный плеер', tag: 'your little soundtrack', text: 'Уникальный встроенный плеер. Любимая музыка живёт рядом с чатами.', detail: 'Отдельный музыкальный интерфейс внутри MioGram — не просто аудиосообщение в переписке. Слушай музыку и управляй воспроизведением, не переключаясь на другое приложение. Сайт показывает возможности клиента, но не запускает его плеер.' },
  { id: 'ai', category: 'ai', symbol: '✦', name: 'Встроенный ИИ', tag: 'a clever companion', text: 'Умные инструменты прямо в клиенте. Немного магии для обычных задач.', detail: 'ИИ-инструменты встроены в MioGram. В репозитории описаны локальное распознавание речи и подключение внешних моделей со своим ключом. Доступность моделей, необходимость интернета и обработка данных зависят от выбранной функции и настроек.' },
  { id: 'layouts', category: 'style', symbol: '▤', name: 'Четыре настроения UI', tag: 'choose your comfort', text: 'Discord, iOS, современный Telegram или старый добрый ТГ.', detail: 'Выбирай визуальный стиль, в котором тебе удобно: Discord, iOS, современный Telegram или привычный классический ТГ. Это варианты оформления Android-клиента, а не отдельные приложения для этих платформ.' },
  { id: 'storage', category: 'tools', symbol: '∞', name: 'Бесконечное хранилище', tag: 'room for your world', text: 'Для файлов, воспоминаний и всего, что хочется оставить рядом.', detail: 'Храни важное в облачном пространстве Telegram через MioGram. «Бесконечное» описывает отсутствие общего лимита облачной коллекции, а не отмену ограничений Telegram: размер отдельного файла и другие условия сервиса по-прежнему действуют.' },
  { id: 'subfolders', category: 'tools', symbol: '⊞', name: 'Подпапки', tag: 'a place for everything', text: 'Больше порядка внутри папок. Даже у самого большого чат-листа.', detail: 'Разделяй большие подборки на подпапки: для работы, друзей, каналов и личных интересов. Дополнительный уровень организации помогает не превращать список чатов в бесконечную ленту.' },
  { id: 'badges', category: 'style', symbol: '୨୧', name: 'Пиксельные бейджики', tag: 'tiny pixels, big personality', text: 'Маленькие знаки отличия с большим характером. Найди свой.', detail: 'У MioGram есть пиксельные бейджи сообщества с разными стилями и историей получения. В репозитории описаны десять вариантов — от нежного Angel до Glitch и Premium. Условия получения зависят от конкретного бейджа.' },
  { id: 'ghost', category: 'privacy', symbol: '♧', name: 'Режим призрака', tag: 'quiet mode, cute soul', text: 'Меньше лишнего внимания к твоей активности. Больше личного пространства.', detail: 'Режим призрака добавляет настройки видимости активности в клиенте. Он не делает аккаунт анонимным и не отменяет серверные правила Telegram. Какие именно события можно скрывать, проверяй в настройках своей версии.' },
  { id: 'deleted', category: 'privacy', symbol: '↶', name: 'Сохранение удалённых', tag: 'a little memory', text: 'Сохраняй историю сообщений, даже если её часть удалили из чата.', detail: 'Функция сохранения удалённых помогает удержать уже полученные сообщения в клиенте. Это не восстановление любых сообщений с серверов Telegram: ранее недоступные или не полученные клиентом сообщения вернуть таким способом нельзя. Учитывай приватность собеседников.' },
  { id: 'updates', category: 'tools', symbol: '↻', name: 'Поиск и установка обновлений', tag: 'always growing', text: 'Новые версии можно найти и установить через сам клиент.', detail: 'Встроенный механизм помогает проверить наличие обновления и перейти к его установке. Android может запросить разрешение на установку или подтверждение пользователя. Вручную актуальные сборки доступны в GitHub Releases.' },
  { id: 'localizer', category: 'tools', symbol: 'あ', name: 'Локализатор', tag: 'speaks your language', text: 'Инструменты локализации, чтобы интерфейс говорил на твоём языке.', detail: 'Локализатор помогает работать с языковым оформлением клиента. Поддерживаемые языки и доступные настройки зависят от сборки. Это отдельная возможность MioGram, а не обещание автоматического перевода всей переписки.' },
  { id: 'news', category: 'ai', symbol: '✧', name: 'Умные ИИ-новости', tag: 'less noise, more meaning', text: 'ИИ помогает ориентироваться в новостях и находить главное.', detail: 'Умные новости используют ИИ для работы с информационным потоком. Относись к результатам как к помощи в чтении, а не как к проверенным фактам: сверяй важные выводы с первоисточниками. Настройки и источники зависят от версии клиента.' },
  { id: 'multichat', category: 'tools', symbol: '▥', name: 'Мультичат', tag: 'more conversations, less fuss', text: 'Несколько разговоров — один удобный рабочий контекст.', detail: 'Мультичат создан для работы с несколькими беседами в клиенте. Держи нужные разговоры под рукой и выбирай удобный способ общения. Возможности отображения зависят от версии и выбранного интерфейса.' },
  { id: 'icons', category: 'style', symbol: '❖', name: 'Кастомные иконки', tag: 'cute from the first tap', text: 'Твой вайб начинается ещё на домашнем экране. Выбери свою иконку.', detail: 'Меняй иконку приложения под любимую тему и оформление телефона. Это ещё одна маленькая деталь персонализации MioGram. Доступный набор иконок зависит от установленной версии.' },
];

export default function FeatureCatalog() {
  const [category, setCategory] = useState('all');
  const [query, setQuery] = useState('');
  const [expanded, setExpanded] = useState<string | null>(null);
  const filtered = items.filter(item => (category === 'all' || item.category === category) && `${item.name} ${item.text} ${item.tag} ${item.detail}`.toLocaleLowerCase('ru').includes(query.trim().toLocaleLowerCase('ru')));
  return (
    <section className="catalog-section container" id="all-features" aria-labelledby="catalog-heading">
      <div className="catalog-window">
        <div className="window-bar"><span>✧ miogram_superpowers.exe</span><span className="catalog-bar-note">{items.length} features & counting ♡</span></div>
        <div className="catalog-content">
          <div className="catalog-heading"><div><div className="section-kicker">МИЛЫЙ — НЕ ЗНАЧИТ ПРОСТОЙ</div><h2 id="catalog-heading">Целый мир фич.<br /><span>В одном MioGram.</span></h2></div><p>От двойного хранилища до собственного плеера.<br />Не только розовый. По-настоящему твой. <span>♡</span></p></div>
          <div className="catalog-toolbar"><div className="catalog-filters" role="group" aria-label="Категории возможностей">{categories.map(c => <button key={c.id} className={category === c.id ? 'selected' : ''} aria-pressed={category === c.id} onClick={() => { setCategory(c.id); setExpanded(null); }}><span aria-hidden="true">{c.symbol}</span>{c.label}</button>)}</div><label className="catalog-search"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="10" cy="10" r="6" /><path d="m15 15 6 6" /></svg><input aria-label="Поиск возможностей" placeholder="Найти свою суперсилу..." value={query} onChange={e => { setQuery(e.target.value); setExpanded(null); }} />{query && <button onClick={() => setQuery('')} aria-label="Очистить поиск">×</button>}</label></div>
          <div className="catalog-result-count" role="status">{query || category !== 'all' ? `Найдено: ${filtered.length} из ${items.length}` : `${items.length} возможностей для твоего цифрового мира`}<span>нажми на карточку — расскажем больше ↙</span></div>
          <div className="catalog-grid">{filtered.map(item => <article className={`catalog-card category-${item.category} ${expanded === item.id ? 'is-expanded' : ''}`} key={item.id}><button className="catalog-card-toggle" aria-expanded={expanded === item.id} aria-controls={`detail-${item.id}`} onClick={() => setExpanded(expanded === item.id ? null : item.id)}><div className="catalog-card-top"><span className="catalog-symbol" aria-hidden="true">{item.symbol}</span><span className="catalog-expand" aria-hidden="true">{expanded === item.id ? '−' : '+'}</span></div><h3>{item.name}</h3><p>{item.text}</p><span className="catalog-card-tag">{item.tag}</span></button><div className="catalog-detail" id={`detail-${item.id}`} hidden={expanded !== item.id}><p>{item.detail}</p>{item.id === 'updates' && <a href={REPO + '/releases'} target="_blank" rel="noreferrer">Открыть релизы ↗</a>}{item.id === 'customization' && <a href="#themes">Попробовать палитры ↓</a>}</div></article>)}</div>
          {filtered.length === 0 && <div className="catalog-empty"><span>（｡•́‿•̀｡）</span><h3>Эта суперсила пока не нашлась</h3><p>Попробуй другое слово или посмотри все возможности.</p><button className="button secondary" onClick={() => { setCategory('all'); setQuery(''); }}>Показать всё ♡</button></div>}
          <p className="catalog-disclaimer">Возможности Android-клиента, не функции этого веб-демо. Доступность и поведение зависят от сборки, устройства и настроек. Подробности — в <a href={REPO + '/releases'} target="_blank" rel="noreferrer">описании релизов ↗</a>.</p>
        </div>
      </div>
      <div className="growing-note"><div className="growing-symbol" aria-hidden="true">✧</div><div><span className="section-kicker">TO BE CONTINUED...</span><h3>И это ещё не конец. <span>Мы только разгоняемся ♡</span></h3><p>Впереди ещё много фич. Следи за развитием MioGram и приноси свои идеи — следующая любимая возможность может начаться с тебя.</p></div><a className="button secondary" href={REPO + '/releases'} target="_blank" rel="noreferrer">Следить за обновлениями ↗</a></div>
    </section>
  );
}
