package app.miogram.bridge.plugins;

import java.util.Locale;

/**
 * Offline fallback scaffold for the Plugin Forge: a valid, compiling Rust
 * plugin template used when the AI model is unreachable (no key / offline).
 * The AI-generated code replaces {@code lib.rs} when available; Cargo.toml
 * and manifest.json always come from here so the layout is stable.
 */
public final class MioForgeScaffold {

    private MioForgeScaffold() {}

    public static String sanitizeId(String raw) {
        String base = raw != null ? raw.trim().toLowerCase(Locale.US) : "custom_plugin";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < base.length(); i++) {
            char c = base.charAt(i);
            if ((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_') {
                sb.append(c);
            } else if (c == ' ' || c == '-' || c == '.') {
                if (sb.length() > 0 && sb.charAt(sb.length() - 1) != '_') sb.append('_');
            }
        }
        String id = sb.toString().replaceAll("_+", "_");
        if (id.isEmpty()) id = "custom_plugin";
        if (id.length() > 40) id = id.substring(0, 40);
        return id;
    }

    public static String structName(String id) {
        StringBuilder sb = new StringBuilder();
        boolean up = true;
        for (int i = 0; i < id.length(); i++) {
            char c = id.charAt(i);
            if (c == '_') {
                up = true;
            } else if (up) {
                sb.append(Character.toUpperCase(c));
                up = false;
            } else {
                sb.append(c);
            }
        }
        if (sb.length() == 0) sb.append("CustomPlugin");
        return sb.toString();
    }

    public static String cargoToml(String id) {
        return "[package]\n"
                + "name = \"" + id + "\"\n"
                + "version = \"0.1.0\"\n"
                + "edition = \"2021\"\n"
                + "description = \"Miogram plugin generated by Plugin Forge\"\n"
                + "license = \"GPL-3.0\"\n"
                + "\n"
                + "[lib]\n"
                + "crate-type = [\"cdylib\"]\n"
                + "\n"
                + "[dependencies]\n"
                + "miogram-plugin-sdk = { git = \"https://github.com/fuckramochka/mioplugin\", package = \"miogram-plugin-sdk\", branch = \"main\" }\n"
                + "\n"
                + "[profile.release]\n"
                + "opt-level = \"z\"\n"
                + "panic = \"abort\"\n"
                + "strip = true\n";
    }

    /** Minimal echo plugin — guaranteed to compile against the SDK. */
    public static String libRs(String id) {
        String s = structName(id);
        return "//! " + id + " — generated by Miogram Plugin Forge.\n"
                + "//! Replace the match arms with real ops; keep the contract:\n"
                + "//! unknown op => Err(1), answers via envelope::encode.\n"
                + "\n"
                + "use miogram_plugin_sdk::{envelope, Plugin};\n"
                + "\n"
                + "#[derive(Default)]\n"
                + "struct " + s + ";\n"
                + "\n"
                + "impl Plugin for " + s + " {\n"
                + "    fn handle(&mut self, op: &str, payload: &[u8]) -> Result<Vec<u8>, i32> {\n"
                + "        match op {\n"
                + "            \"ping\" => Ok(envelope::encode(\"ping\", b\"pong\")),\n"
                + "            \"echo\" => Ok(envelope::encode(\"echo\", payload)),\n"
                + "            _ => Err(1),\n"
                + "        }\n"
                + "    }\n"
                + "}\n"
                + "\n"
                + "miogram_plugin_sdk::register!(" + s + ");\n"
                + "\n"
                + "#[allow(dead_code)]\n"
                + "fn main() {}\n";
    }

    public static String manifestJson(String id, String name, String description, String category) {
        return manifestJson(id, name, description, category, "rust");
    }

    public static String manifestJson(String id, String name, String description, String category, String language) {
        String safeName = name != null && !name.trim().isEmpty() ? name.trim() : id;
        String safeDesc = description != null ? description : "";
        String safeCat = category != null && !category.trim().isEmpty() ? category.trim() : "Utility";
        String entry = "go".equalsIgnoreCase(language) ? "plugin.wasm" : "plugin.wasm";
        return "{\n"
                + "  \"id\": \"" + id + "\",\n"
                + "  \"name\": \"" + safeName.replace("\"", "'") + "\",\n"
                + "  \"version\": \"0.1.0\",\n"
                + "  \"author\": \"Plugin Forge\",\n"
                + "  \"description\": \"" + safeDesc.replace("\"", "'").replace("\n", " ") + "\",\n"
                + "  \"category\": \"" + safeCat.replace("\"", "'") + "\",\n"
                + "  \"icon\": \"msg_games\",\n"
                + "  \"entry_point\": \"" + entry + "\",\n"
                + "  \"language\": \"" + ("go".equalsIgnoreCase(language) ? "go" : "rust") + "\",\n"
                + "  \"abi\": 1,\n"
                + "  \"min_app_version\": \"1.0.0\"\n"
                + "}\n";
    }

    public static String goMod(String id) {
        return "module " + id + "\n\ngo 1.21\n";
    }

    /**
     * Minimal echo plugin in Go (TinyGo-compatible: no cgo, no net, no
     * goroutines). Speaks the same C ABI + MIOG envelope as the Rust SDK:
     * build with {@code tinygo build -o plugin.wasm -target wasm .}
     */
    public static String goMain(String id) {
        return "// " + id + " - generated by Miogram Plugin Forge (Go/TinyGo).\n"
                + "// Build: tinygo build -o plugin.wasm -target wasm .\n"
                + "package main\n"
                + "\n"
                + "import \"unsafe\"\n"
                + "\n"
                + "// live keeps guest buffers alive until the host frees them.\n"
                + "var live = make(map[int32][]byte)\n"
                + "\n"
                + "//export miogram_abi_version\n"
                + "func miogram_abi_version() int32 { return 1 }\n"
                + "\n"
                + "//export miogram_alloc\n"
                + "func miogram_alloc(size int32) int32 {\n"
                + "\tif size <= 0 {\n"
                + "\t\treturn 0\n"
                + "\t}\n"
                + "\tbuf := make([]byte, size)\n"
                + "\tptr := int32(uintptr(unsafe.Pointer(&buf[0])))\n"
                + "\tlive[ptr] = buf\n"
                + "\treturn ptr\n"
                + "}\n"
                + "\n"
                + "//export miogram_guest_free\n"
                + "func miogram_guest_free(ptr int32, length int32) {\n"
                + "\tdelete(live, ptr)\n"
                + "}\n"
                + "\n"
                + "func encode(op string, payload []byte) []byte {\n"
                + "\tout := make([]byte, 0, 12+len(op)+len(payload))\n"
                + "\tout = append(out, 'M', 'I', 'O', 'G', 1, 0, 0, 0)\n"
                + "\tn := uint32(len(op))\n"
                + "\tout = append(out, byte(n), byte(n>>8), byte(n>>16), byte(n>>24))\n"
                + "\tout = append(out, op...)\n"
                + "\tout = append(out, payload...)\n"
                + "\treturn out\n"
                + "}\n"
                + "\n"
                + "func decode(buf []byte) (string, []byte, bool) {\n"
                + "\tif len(buf) < 12 {\n"
                + "\t\treturn \"\", nil, false\n"
                + "\t}\n"
                + "\tif buf[0] != 'M' || buf[1] != 'I' || buf[2] != 'O' || buf[3] != 'G' || buf[4] != 1 {\n"
                + "\t\treturn \"\", nil, false\n"
                + "\t}\n"
                + "\tn := uint32(buf[8]) | uint32(buf[9])<<8 | uint32(buf[10])<<16 | uint32(buf[11])<<24\n"
                + "\tif n > 128 || 12+int(n) > len(buf) {\n"
                + "\t\treturn \"\", nil, false\n"
                + "\t}\n"
                + "\treturn string(buf[12 : 12+n]), buf[12+n:], true\n"
                + "}\n"
                + "\n"
                + "func respond(payload []byte) int64 {\n"
                + "\tptr := miogram_alloc(int32(len(payload)))\n"
                + "\tif ptr == 0 {\n"
                + "\t\treturn -1\n"
                + "\t}\n"
                + "\tcopy(live[ptr], payload)\n"
                + "\treturn (int64(ptr) << 32) | int64(uint32(len(payload)))\n"
                + "}\n"
                + "\n"
                + "//export miogram_call\n"
                + "func miogram_call(ptr int32, length int32) int64 {\n"
                + "\tif ptr == 0 || length < 12 {\n"
                + "\t\treturn -1\n"
                + "\t}\n"
                + "\treq := unsafe.Slice((*byte)(unsafe.Pointer(uintptr(ptr))), length)\n"
                + "\top, payload, ok := decode(req)\n"
                + "\tif !ok {\n"
                + "\t\treturn -2\n"
                + "\t}\n"
                + "\tswitch op {\n"
                + "\tcase \"ping\":\n"
                + "\t\treturn respond(encode(\"ping\", []byte(\"pong\")))\n"
                + "\tcase \"echo\":\n"
                + "\t\treturn respond(encode(\"echo\", payload))\n"
                + "\tdefault:\n"
                + "\t\treturn -1\n"
                + "\t}\n"
                + "}\n"
                + "\n"
                + "func main() {}\n";
    }

    public static String buildInstructions(String id) {
        return buildInstructions(id, "rust");
    }

    public static String buildInstructions(String id, String language) {
        if ("go".equalsIgnoreCase(language)) {
            return "Desktop build (produces plugin.wasm):\n"
                    + "  tinygo build -o plugin.wasm -target wasm .\n"
                    + "Requires TinyGo 0.30+. Then drop plugin.wasm next to manifest.json.";
        }
        return "Desktop build (produces target/wasm32-unknown-unknown/release/" + id + ".wasm):\n"
                + "  cargo build --release --target wasm32-unknown-unknown\n"
                + "Then drop the .wasm next to manifest.json or publish it to the mioplugin repo.";
    }
}
