package app.miogram.bridge.plugins;

import java.util.Locale;

/**
 * Offline fallback scaffold for the Plugin Forge: a valid, compiling Rust
 * plugin template used when the AI model is unreachable (no key / offline).
 * The AI-generated code replaces {@code lib.rs} when available; Cargo.toml
 * and manifest.json always come from here so the layout is stable.
 */
public final class MioForgeScaffold {

    private MioForgeScaffold() {}

    public static String sanitizeId(String raw) {
        String base = raw != null ? raw.trim().toLowerCase(Locale.US) : "custom_plugin";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < base.length(); i++) {
            char c = base.charAt(i);
            if ((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_') {
                sb.append(c);
            } else if (c == ' ' || c == '-' || c == '.') {
                if (sb.length() > 0 && sb.charAt(sb.length() - 1) != '_') sb.append('_');
            }
        }
        String id = sb.toString().replaceAll("_+", "_");
        if (id.isEmpty()) id = "custom_plugin";
        if (id.length() > 40) id = id.substring(0, 40);
        return id;
    }

    public static String structName(String id) {
        StringBuilder sb = new StringBuilder();
        boolean up = true;
        for (int i = 0; i < id.length(); i++) {
            char c = id.charAt(i);
            if (c == '_') {
                up = true;
            } else if (up) {
                sb.append(Character.toUpperCase(c));
                up = false;
            } else {
                sb.append(c);
            }
        }
        if (sb.length() == 0) sb.append("CustomPlugin");
        return sb.toString();
    }

    public static String cargoToml(String id) {
        return "[package]\n"
                + "name = \"" + id + "\"\n"
                + "version = \"0.1.0\"\n"
                + "edition = \"2021\"\n"
                + "description = \"Miogram plugin generated by Plugin Forge\"\n"
                + "license = \"GPL-3.0\"\n"
                + "\n"
                + "[lib]\n"
                + "crate-type = [\"cdylib\"]\n"
                + "\n"
                + "[dependencies]\n"
                + "miogram-plugin-sdk = { git = \"https://github.com/fuckramochka/mioplugin\", package = \"miogram-plugin-sdk\", branch = \"main\" }\n"
                + "\n"
                + "[profile.release]\n"
                + "opt-level = \"z\"\n"
                + "panic = \"abort\"\n"
                + "strip = true\n";
    }

    /** Minimal echo plugin — guaranteed to compile against the SDK. */
    public static String libRs(String id) {
        String s = structName(id);
        return "//! " + id + " — generated by Miogram Plugin Forge.\n"
                + "//! Replace the match arms with real ops; keep the contract:\n"
                + "//! unknown op => Err(1), answers via envelope::encode.\n"
                + "\n"
                + "use miogram_plugin_sdk::{envelope, Plugin};\n"
                + "\n"
                + "#[derive(Default)]\n"
                + "struct " + s + ";\n"
                + "\n"
                + "impl Plugin for " + s + " {\n"
                + "    fn handle(&mut self, op: &str, payload: &[u8]) -> Result<Vec<u8>, i32> {\n"
                + "        match op {\n"
                + "            \"ping\" => Ok(envelope::encode(\"ping\", b\"pong\")),\n"
                + "            \"echo\" => Ok(envelope::encode(\"echo\", payload)),\n"
                + "            _ => Err(1),\n"
                + "        }\n"
                + "    }\n"
                + "}\n"
                + "\n"
                + "miogram_plugin_sdk::register!(" + s + ");\n"
                + "\n"
                + "#[allow(dead_code)]\n"
                + "fn main() {}\n";
    }

    public static String manifestJson(String id, String name, String description, String category) {
        String safeName = name != null && !name.trim().isEmpty() ? name.trim() : id;
        String safeDesc = description != null ? description : "";
        String safeCat = category != null && !category.trim().isEmpty() ? category.trim() : "Utility";
        return "{\n"
                + "  \"id\": \"" + id + "\",\n"
                + "  \"name\": \"" + safeName.replace("\"", "'") + "\",\n"
                + "  \"version\": \"0.1.0\",\n"
                + "  \"author\": \"Plugin Forge\",\n"
                + "  \"description\": \"" + safeDesc.replace("\"", "'").replace("\n", " ") + "\",\n"
                + "  \"category\": \"" + safeCat.replace("\"", "'") + "\",\n"
                + "  \"icon\": \"msg_games\",\n"
                + "  \"entry_point\": \"plugin.wasm\",\n"
                + "  \"abi\": 1,\n"
                + "  \"min_app_version\": \"1.0.0\"\n"
                + "}\n";
    }

    public static String buildInstructions(String id) {
        return "Desktop build (produces target/wasm32-unknown-unknown/release/" + id + ".wasm):\n"
                + "  cargo build --release --target wasm32-unknown-unknown\n"
                + "Then drop the .wasm next to manifest.json or publish it to the mioplugin repo.";
    }
}
