[package]
name = "miogram_in_app_notifications"
version = "2.0.0"
edition = "2021"
authors = ["Miogram Team <dev@miogram.app>"]
description = "High-performance native WebAssembly In-App Notification engine for Miogram"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
